- hosts: localhost 
  become: true
  become_user: root
  
  tasks:
    - name: Docker Pull
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - centos/httpd
        - nginx
    - name: Create docker images
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        ports: "{{ item.ports }}"
      with_items:
        - { name: 'apache1', image: 'centos/httpd', ports: '8383:80' }   
        - { name: 'apache2', image: 'centos/httpd', ports: '8484:80' }
        - { name: 'nginx', image: 'nginx', ports: '8989:80' }
    - name: Copy files to docker
      command: "{{ item }}" 
      with_items:
        - docker cp /home/vagrant/apache1/index.html apache1:/var/www/html/index.html
        - docker cp /home/vagrant/apache2/index.html apache2:/var/www/html/index.html
        - docker cp /home/vagrant/nginx/nginx.conf nginx:/etc/nginx/nginx.conf
        - docker exec nginx nginx -s reload
